<template>
  <div>
    <section class="page-section bg-light" id="about">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4 class="notice__title mb-5">Legal Notice</h4>
            <ul class="notice_main_ul">
              <li class="main_li">
                <span class="font-weight-bold">Use of Google Analytics for web analysis</span>
                <ul class="notice_sub_ul">
                  <li>This website uses Google Analytics, a web analysis service of Google Inc. (www.google.de). Google Analytics uses so-called 'cookies', text files that are saved to your computer that enable analysis of how you use the website. The information generated by the cookie about the way you use the website is as a rule transmitted to a Google Server in the USA and stored there. However, if IP anonymisation has been activated on this website, your IP address will be truncated by Google within the member states of the European Union or other states who are party to the Agreement on the European Economic Area. Only in exceptional cases will the full IP address be transferred to a server of Google in the USA and truncated there. IP anonymisation is active on this website. On behalf of the operator of this website, Google will use this information to evaluate your use of the website, to compile reports of the website activities and to perform further services for the website operator related to website and Internet use. The IP address transmitted by your browser as part of Google Analytics will not be merged with other Google data. You can prevent the storage of cookies by making appropriate settings in your browser software. However, we advise you that if you do this you may not be able to use all of the website's functions to their full extent.</li>
                  <li>As an alternative to the browser plugin, you can click on this link to prevent Google Analytics from collecting data on this website in future. This will cause an opt-out cookie to be saved on your device. If you delete your cookies, you will have to click on the link again.</li>
                </ul>
              </li>
              <li class="main_li">
                <span class="font-weight-bold">Privacy statement</span>
                <ul class="notice_sub_ul">
                  <li>We are glad that you have chosen to visit our website and we appreciate your interest in our company and products. Investors rating.com stakes the protection of your personal data seriously; we want you to feel secure while visiting our Internet site. We process the data collected when your visit our web pages in accordance with the applicable data protection regulations in the French law. Web pages may contain links to pages of other providers which are not covered by this privacy statement.</li>
                </ul>
              </li>
              <li class="main_li">
                <span class="font-weight-bold">Collection and processing of personal data</span>
                <ul class="notice_sub_ul">
                  <li>By default, when you visit our web pages, our web servers save the name of your Internet service provider, the website through which you came to our site, the web pages that you visit on our site, and the date and duration of your visit. No personal data is collected. This only happens when you provide us with this data yourself, for example during a registration, survey, or competition or when implementing a contract.</li>
                </ul>
              </li>
              <li class="main_li">
                <span
                  class="font-weight-bold"
                >Use and disclosure of personal data and purpose limitation</span>
                <ul class="notice_sub_ul">
                  <li>Vitakraft uses your personal data for the purposes of performing the technical administration of our web pages, customer management, product surveys and marketing, to the extent necessary in each case. We will only pass on your personal data to a third party to the extent necessary for performing the requested service. The transmission of your personal data to governmental institutions and authorities is only performed within the scope of binding national legal provisions. Addresses collected during competitions and marketing campaigns are deleted once they have been concluded.</li>
                </ul>
              </li>
              <li class="main_li">
                <span class="font-weight-bold">Option</span>
                <ul class="notice_sub_ul">
                  <li>Vitakraft wishes to use your data to inform you of our products and, where relevant, to ask you about them. Participation in such campaigns is of course voluntary. If you do not wish us to do this, you can notify us at any time so that we can block your data from such use.</li>
                </ul>
              </li>
              <li class="main_li">
                <span class="font-weight-bold">Cookies</span>
                <ul class="notice_sub_ul">
                  <li>Investor ratings,com uses cookies. Cookies are small files that are saved temporarily on your hard drive. The information contained in the cookies serves to simplify navigation and considerably enhances a website's user friendliness. Our cookies contain no specific personal information, which means that your privacy is protected. Most browsers accept cookies automatically. Cookies help us to track the preferences of visitors to our websites, which enables us to design our web pages with optimum regard for our visitors' wishes and interests. You can of course view our website without the use of cookies. You can prevent cookies being saved to your hard drive by selecting the option 'Do not accept cookies' in your browser settings. Precise details on how to do this can be found in the manual of your browser manufacturer. Not accepting cookies may limit the functionality of our offers.</li>
                </ul>
              </li>
              <li class="main_li">
                <span class="font-weight-bold">Right to information</span>
                <ul class="notice_sub_ul">
                  <li>Upon request, Investors rating.Com will inform you without delay and in line with applicable law of whether and what personal data we have stored about you. Should the information we have stored be incorrect, despite our efforts to ensure data is accurate and up to date, we will correct this when instructed by you to do so.</li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: "Notice",
  data() {
    return {};
  },
  mounted() {
    document.title = "Legal Notice";
  }
};
</script>
<style lang="scss">
.notice__title {
  color: #f4623a;
}
.notice_main_ul {
  .main_li {
    text-align: left;
  }
  .notice_sub_ul {
    margin-top: 15px;
    li {
      text-align: left;
      margin-bottom: 10px;
    }
  }
}
</style>
